name: Trigger auto deployment for pers-engine-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pers-engine-backend-AutoDeployTrigger-bdda6b03-d44e-477c-8b0b-ba00fd0bad9f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PERSENGINEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PERSENGINEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PERSENGINEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Dockerfile.backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: persengineacr.azurecr.io
          registryUsername: ${{ secrets.PERSENGINEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PERSENGINEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: pers-engine-backend
          resourceGroup: pers-engine-rg
          imageToBuild: persengineacr.azurecr.io/pers-engine-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


